cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.erudio.com.br
spring:
  application:
    name: aprendendo-spring-boot-com-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aprendendo_spring_boot_com_java_2?useTimezone=true&serverTimezone=UTC
    username: toor
    password: 5tgb6yhn
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    root: INFO
    # root: WARN
    # br.com.erudio: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true